steps:

  - id: "Rodando ENV"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
    args: ['-f','docker-compose.yaml','run','app','go','test']

  - id: "Send image Google Container Registry"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/golang-sum:latest','.']
    images:
      - 'gcr.io/$PROJECT_ID/golang-sum:latest'